spring:
  profiles: dev

python:
  # python脚本路径
  path: D:\IdeaProjects\project\gdou-jw-tools\src\main\resources\python\
  name: slide_captcha_pass.py
  # python命令行输出的字符编码，在不同环境下运行需要进行不同的设置：Windows下为GBK，Linux下为UTF-8
  output-encoding: GBK